# Generated by Django 4.2.3 on 2023-08-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('latest_delivery_address', models.TextField()),
                ('latest_latitude', models.FloatField()),
                ('latest_longitude', models.FloatField()),
            ],
        ),
    ]
