# Generated by Django 4.2.3 on 2023-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.TextField(default=None),
        ),
    ]
